

## ```
# Run Each cell one by one
```



In [ ]:
#Import required data from drive
from google.colab import drive
drive.mount('/content/drive/')

Go to this URL in a browser: https://accounts.google.com/o/oauth2/auth?client_id=947318989803-6bn6qk8qdgf4n4g3pfee6491hc0brc4i.apps.googleusercontent.com&redirect_uri=urn%3aietf%3awg%3aoauth%3a2.0%3aoob&scope=email%20https%3a%2f%2fwww.googleapis.com%2fauth%2fdocs.test%20https%3a%2f%2fwww.googleapis.com%2fauth%2fdrive%20https%3a%2f%2fwww.googleapis.com%2fauth%2fdrive.photos.readonly%20https%3a%2f%2fwww.googleapis.com%2fauth%2fpeopleapi.readonly&response_type=code

Enter your authorization code:
··········
Mounted at /content/drive/


In [ ]:

# In following sections, the g-gap features are further processed to shape them as a CNN input




#%%
c="/content/drive/My Drive/Colab Notebooks/allseq.csv"  #Folder path in drive where all sequences of benchmarking dataset is.
with open(c) as f:
    content = f.read() 
s=0
dat=content.split("\n") 
for i in dat:
    dat[s]=list(dat[s])
    s=s+1
          

    
import numpy as np
lm=1
tp=np.zeros(1826)
for h in range(1826):
    tp[h]=len(dat[lm])
    lm=lm+2
#%%
c="/content/drive/My Drive/Colab Notebooks/fet_all_0.csv"  #Folder path in drive where all g-gap DPC features with gap 0 is.
with open(c) as f:
    content0 = f.read() 
    
dat0=content0.split("\n") 
s=0
for i in range(len(dat0)):
    dat0[s]=dat0[s].split(",")
    s=s+1
    
   
import numpy as np
dataaa0=np.zeros((1826,400))
ii=0; jj=0
for i in range(1826):
    for j in range(400):
        dataaa0[i][j]=float(dat0[i][j])
        

    
#%%
c="/content/drive/My Drive/Colab Notebooks/fet_all_1.csv"  #Folder path in drive where all g-gap DPC features with gap 1 is.
with open(c) as f:
    content1 = f.read() 
    
dat1=content1.split("\n") 
s=0
for i in range(len(dat1)):
    dat1[s]=dat1[s].split(",")
    s=s+1
    
   
import numpy as np
dataaa1=np.zeros((1826,400))
ii=0; jj=0
for i in range(1826):
    for j in range(400):
        dataaa1[i][j]=float(dat1[i][j])
        

    
#%%
c="/content/drive/My Drive/Colab Notebooks/all_fet_2.csv"  #Folder path in drive where all g-gap DPC features with gap 2 is.
with open(c) as f:
    content2 = f.read() 
    
dat2=content2.split("\n") 
s=0
for i in range(len(dat2)):
    dat2[s]=dat2[s].split(",")
    s=s+1
    
   
import numpy as np
dataaa2=np.zeros((1826,400))
ii=0; jj=0
for i in range(1826):
    for j in range(400):
        dataaa2[i][j]=float(dat2[i][j])
        

#%%
c="/content/drive/My Drive/Colab Notebooks/fet_all_3.csv"  #Folder path in drive where all g-gap DPC features with gap 3 is.
with open(c) as f:
    content3 = f.read() 
    
dat3=content3.split("\n") 
s=0
for i in range(len(dat3)):
    dat3[s]=dat3[s].split(",")
    s=s+1
    
   
import numpy as np
dataaa3=np.zeros((1826,400))
ii=0; jj=0
for i in range(1826):
    for j in range(400):
        dataaa3[i][j]=float(dat3[i][j])
        
   

## As we have four types of g-gap DPC (with gap 0,1,2, and 3) features, from these four DPC features we  have created four different combinations and created RGB images from them. in next 4 steps four types of images are created. 

In [ ]:
#Images for DPC features with gap 0,1,2
a = np.reshape(dataaa0,[1826,20,20])
b = np.reshape(dataaa1,[1826,20,20])
c = np.reshape(dataaa2,[1826,20,20])
feature1=np.zeros((1826,20,20,3))
for i in range(1826):
  data = np.zeros( (20,20,3))
  data[:,:,0]=a[i,:,:]
  data[:,:,1]=b[i,:,:]
  data[:,:,2]=c[i,:,:]
  feature1[i]=data     

In [ ]:
#Images for DPC features with gap 0,1,3
a = np.reshape(dataaa0,[1826,20,20])
b = np.reshape(dataaa1,[1826,20,20])
c = np.reshape(dataaa3,[1826,20,20])
feature2=np.zeros((1826,20,20,3))
for i in range(1826):
  data = np.zeros( (20,20,3))
  data[:,:,0]=a[i,:,:]
  data[:,:,1]=b[i,:,:]
  data[:,:,2]=c[i,:,:]
  feature2[i]=data 

In [ ]:
#Images for DPC features with gap 0,2,3
a = np.reshape(dataaa0,[1826,20,20])
b = np.reshape(dataaa2,[1826,20,20])
c = np.reshape(dataaa3,[1826,20,20])
feature3=np.zeros((1826,20,20,3))
for i in range(1826):
  data = np.zeros( (20,20,3))
  data[:,:,0]=a[i,:,:]
  data[:,:,1]=b[i,:,:]
  data[:,:,2]=c[i,:,:]
  feature3[i]=data 

In [ ]:
#Images for DPC features with gap 1,2,3
a = np.reshape(dataaa1,[1826,20,20])
b = np.reshape(dataaa2,[1826,20,20])
c = np.reshape(dataaa3,[1826,20,20])
feature4=np.zeros((1826,20,20,3))
for i in range(1826):
  data = np.zeros( (20,20,3))
  data[:,:,0]=a[i,:,:]
  data[:,:,1]=b[i,:,:]
  data[:,:,2]=c[i,:,:]
  feature4[i]=data

In [ ]:
#%% Generating Label Vector
import numpy as np
label=np.zeros(1826)
for i in range(913):
    label[i]=0
j=913  
for k in range(913):
    label[j]=1
    j=j+1

In [ ]:
#% shuffeling the data
 
from sklearn.utils import shuffle
features1,features2,features3,features4,labels=shuffle(feature1,feature2,feature3,feature4,label, random_state=1)


In [ ]:
import os,cv2
import numpy as np
import matplotlib.pyplot as plt

from sklearn.utils import shuffle
from sklearn.model_selection import train_test_split

from keras import backend as K
K.set_image_data_format('channels_last')




from keras.utils import np_utils
from keras.models import Sequential
from keras.layers  import Dense, Dropout, Activation, Flatten
from keras.layers import Conv2D, MaxPooling2D
!pip install adam
import adam
from keras.optimizers import SGD,RMSprop#adam#
from keras.models import Sequential
from keras.layers import Dense
from sklearn.model_selection import StratifiedKFold
import numpy
from keras.callbacks import ModelCheckpoint
from keras.models import Sequential
from keras.layers import Dense
from keras.callbacks import ModelCheckpoint
import matplotlib.pyplot as plt
import numpy

# Generating four CNN models and saving them in drive

In [ ]:
#%% Training CNN for First type of Images (Gap with 0,1,2 (Features1))
seed = 1
numpy.random.seed(seed)
kfold = StratifiedKFold(n_splits=10, shuffle=True, random_state=seed)
cvscores = []
testing=[]
pred=[]
i=1
for train, test in kfold.split(features1, labels): #.......................................................
  model = Sequential()
  model.add(Conv2D(32, (3, 3),  input_shape=features1[0].shape))#.......................................................
  convout1 = Activation('relu')
  model.add(convout1)
  convout3 = Activation('relu')
  model.add(convout3)
  model.add(Conv2D(8,( 3, 3)))
  
  model.add(MaxPooling2D(pool_size=(2,2 )))
  model.add(Dropout(0.5))

  model.add(Flatten())
  model.add(Dense(170))
  model.add(Activation('relu'))
  model.add(Dropout(0.5))
  model.add(Dense(1))
  model.add(Activation('sigmoid'))
  model.compile(loss='binary_crossentropy', optimizer='adam', metrics=["accuracy"])
  ii=str(i)
  filepath="/content/drive/My Drive/Colab Notebooks/new-weights-bench-cv10-0,1,2-NC-"+ii+".hdf5"  #.......................................................
  checkpoint = ModelCheckpoint(filepath, monitor='val_accuracy', verbose=1, save_best_only=True, mode='max', period=1)
  callbacks_list = [checkpoint]
	# Fit the model
  model.fit(features1[train], labels[train], batch_size=35, epochs=370, verbose=1, validation_data=(features1[test], labels[test]), callbacks=[checkpoint]) #.......................................................
  score2=model.evaluate(features1[train],labels[train],verbose=0) #..............................
  print("acuuurcy:")
  print(score2)
  model = Sequential()
  model.add(Conv2D(32, (3, 3),  input_shape=features1[0].shape)) #.......................................................
  convout1 = Activation('relu')
  model.add(convout1)
  convout3 = Activation('relu')
  model.add(convout3)
  model.add(Conv2D(8,( 3, 3)))
  
  model.add(MaxPooling2D(pool_size=(2,2 )))
  model.add(Dropout(0.5))
  model.add(Flatten())
  model.add(Dense(170))
  model.add(Activation('relu'))
  model.add(Dropout(0.5))
  model.add(Dense(1))
  model.add(Activation('sigmoid'))
  #model.compile(loss='binary_crossentropy', optimizer='adam', metrics=["accuracy"])
# load weights
  model.load_weights(filepath)
# Compile model (required to make predictions)
  model.compile(loss='binary_crossentropy', optimizer='adam', metrics=["accuracy"])
  print("Created model and loaded weights from file")
# load pima indians dataset
  score2=model.evaluate(features1[train],labels[train],verbose=0) #.......................................................
  print("acuuuraaacy:")
  print(score2)
  scores = model.evaluate(features1[test], labels[test], verbose=0) #.......................................................
  print("%s: %.2f%%" % (model.metrics_names[1], scores[1]*100))
  cvscores.append(scores[1] * 100)
  p = model.predict_classes(features1[test])  #.......................................................     
  pred.append(p)
  testing.append(labels[test]) 
  i=i+1
print("%.2f%% (+/- %.2f%%)" % (numpy.mean(cvscores), numpy.std(cvscores)))


Streaming output truncated to the last 5000 lines.
36/47 [=====================>........] - ETA: 0s - loss: 0.0780 - accuracy: 0.9722
Epoch 00238: val_accuracy did not improve from 0.82418
47/47 [==============================] - 0s 3ms/step - loss: 0.0721 - accuracy: 0.9751 - val_loss: 0.6313 - val_accuracy: 0.7802
Epoch 239/370
38/47 [=======================>......] - ETA: 0s - loss: 0.0689 - accuracy: 0.9789
Epoch 00239: val_accuracy did not improve from 0.82418
47/47 [==============================] - 0s 3ms/step - loss: 0.0692 - accuracy: 0.9757 - val_loss: 0.6902 - val_accuracy: 0.7802
Epoch 240/370
38/47 [=======================>......] - ETA: 0s - loss: 0.0687 - accuracy: 0.9737
Epoch 00240: val_accuracy did not improve from 0.82418
47/47 [==============================] - 0s 3ms/step - loss: 0.0674 - accuracy: 0.9738 - val_loss: 0.7665 - val_accuracy: 0.7912
Epoch 241/370
37/47 [======================>.......] - ETA: 0s - loss: 0.0843 - accuracy: 0.9722
Epoch 00241: val_accura

In [ ]:
# Calculating performance estimators for first CNN model
from sklearn.metrics import matthews_corrcoef
#import keras_metrics
#from keras import backend as K
from sklearn.metrics import confusion_matrix
from sklearn.metrics import classification_report
#import keras_metrics as km
from sklearn.metrics import f1_score 
a = np.array(pred)
aa= []
for sublist in a:
    for val in sublist:
        aa.append(val)

b= np.array(testing)
bb= []
for sublist in b:
    for val in sublist:
        bb.append(val)
sensitivity1=np.zeros(10) #...........................
specificity1=np.zeros(10) #...........................
mcc=np.zeros(10)  #...........................
accuracy1=np.zeros(10) #...........................
aucc=np.zeros(10) #...........................
tp=np.zeros(10) #...........................
fp=np.zeros(10) #...........................
fn=np.zeros(10) #...........................
tn=np.zeros(10) #...........................
for i in range(10): #...........................
  print('All observations for model', i)
  #%% sensitivity and specificity
  cm1 = confusion_matrix(b[i], a[i])
  sensitivity1[i] = cm1[0,0]/(cm1[0,0]+cm1[0,1])
  print('Sensitivity : ', sensitivity1[i] )

  specificity1[i] = cm1[1,1]/(cm1[1,0]+cm1[1,1])
  print('Specificity : ', specificity1[i])
  tp[i]=cm1[0,0]
  print('tp : ', tp[i])
  fp[i]=cm1[0,1]
  print('fp : ', fp[i])
  fn[i]=cm1[1,0]
  print('fn : ', fn[i])
  tn[i]=cm1[1,0]
  print('tn : ', tn[i])
  #%%
  from sklearn.metrics import matthews_corrcoef
  mcc[i] = matthews_corrcoef(b[i],a[i])
  print('Matthews Correlation Coefficient:', mcc[i])

  #%%
  total1=sum(sum(cm1))

  accuracy1[i]=(cm1[0,0]+cm1[1,1])/total1
  print ('Accuracy : ', accuracy1[i])

  import numpy as np
  from sklearn import metrics
  fpr, tpr, thresholds = metrics.roc_curve(b[i], a[i])
  aucc[i]=metrics.auc(fpr, tpr)
  print('AUC:', aucc[i])
  
print("AVG OF ALL:")
print('Sensitivity : ', np.mean(sensitivity1) )
print('Specificity : ', np.mean(specificity1))
print('Matthews Correlation Coefficient:', np.mean(mcc))
print('AUC:', np.mean(aucc))
print ('Accuracy : ', np.mean(accuracy1))
print('tp:',np.mean(tp))
print('fp:',np.mean(fp))
print('tn:',np.mean(tn))
print('fn:',np.mean(fn))

All observations for model 0
Sensitivity :  0.8043478260869565
Specificity :  0.8571428571428571
tp :  74.0
fp :  18.0
fn :  13.0
tn :  13.0
Matthews Correlation Coefficient: 0.6622822243568666
Accuracy :  0.8306010928961749
AUC: 0.8307453416149069
All observations for model 1
Sensitivity :  0.8804347826086957
Specificity :  0.7692307692307693
tp :  81.0
fp :  11.0
fn :  21.0
tn :  21.0
Matthews Correlation Coefficient: 0.6539760648140381
Accuracy :  0.825136612021858
AUC: 0.8248327759197325
All observations for model 2
Sensitivity :  0.9021739130434783
Specificity :  0.7362637362637363
tp :  83.0
fp :  9.0
fn :  24.0
tn :  24.0
Matthews Correlation Coefficient: 0.6477902614023426
Accuracy :  0.819672131147541
AUC: 0.8192188246536073
All observations for model 3
Sensitivity :  0.8241758241758241
Specificity :  0.7717391304347826
tp :  75.0
fp :  16.0
fn :  21.0
tn :  21.0
Matthews Correlation Coefficient: 0.5966280276844361
Accuracy :  0.7978142076502732
AUC: 0.7979574773053034
All obs

In [ ]:
#%% Training CNN for Second type of Images (Gap with 0,1,3 (Features2))
seed = 1
numpy.random.seed(seed)
kfold = StratifiedKFold(n_splits=10, shuffle=True, random_state=seed)
cvscores = []
testing=[]
pred=[]
i=1
for train, test in kfold.split(features2, labels): #.......................................................
  model = Sequential()
  model.add(Conv2D(32, (3, 3),  input_shape=features2[0].shape))#.......................................................
  convout1 = Activation('relu')
  model.add(convout1)
  convout3 = Activation('relu')
  model.add(convout3)
  model.add(Conv2D(8,( 3, 3)))
  
  model.add(MaxPooling2D(pool_size=(2,2 )))
  model.add(Dropout(0.5))

  model.add(Flatten())
  model.add(Dense(170))
  model.add(Activation('relu'))
  model.add(Dropout(0.5))
  model.add(Dense(1))
  model.add(Activation('sigmoid'))
  model.compile(loss='binary_crossentropy', optimizer='adam', metrics=["accuracy"])
  ii=str(i)
  filepath="/content/drive/My Drive/Colab Notebooks/nnew-weights-bench-cv10-0,1,3-NC-"+ii+".hdf5"  #.......................................................
  checkpoint = ModelCheckpoint(filepath, monitor='val_accuracy', verbose=1, save_best_only=True, mode='max')
  callbacks_list = [checkpoint]
	# Fit the model
  model.fit(features2[train], labels[train], batch_size=35, epochs=370, verbose=1, validation_data=(features2[test], labels[test]),callbacks=callbacks_list) #.......................................................
  score2=model.evaluate(features2[train],labels[train],verbose=0) #..............................
  print("acuuurcy:")
  print(score2)
  model = Sequential()
  model.add(Conv2D(32, (3, 3),  input_shape=features2[0].shape)) #.......................................................
  convout1 = Activation('relu')
  model.add(convout1)
  convout3 = Activation('relu')
  model.add(convout3)
  model.add(Conv2D(8,( 3, 3)))
  
  model.add(MaxPooling2D(pool_size=(2,2 )))
  model.add(Dropout(0.5))
  model.add(Flatten())
  model.add(Dense(170))
  model.add(Activation('relu'))
  model.add(Dropout(0.5))
  model.add(Dense(1))
  model.add(Activation('sigmoid'))
  #model.compile(loss='binary_crossentropy', optimizer='adam', metrics=["accuracy"])
# load weights
  model.load_weights(filepath)
# Compile model (required to make predictions)
  model.compile(loss='binary_crossentropy', optimizer='adam', metrics=["accuracy"])
  print("Created model and loaded weights from file")
# load pima indians dataset
  score2=model.evaluate(features2[train],labels[train],verbose=0) #.......................................................
  print("acuuuraaacy:")
  print(score2)
  scores = model.evaluate(features2[test], labels[test], verbose=0) #.......................................................
  print("%s: %.2f%%" % (model.metrics_names[1], scores[1]*100))
  cvscores.append(scores[1] * 100)
  p = model.predict_classes(features2[test])  #.......................................................     
  pred.append(p)
  testing.append(labels[test]) 
  i=i+1
print("%.2f%% (+/- %.2f%%)" % (numpy.mean(cvscores), numpy.std(cvscores)))


Streaming output truncated to the last 5000 lines.
Epoch 00237: val_accuracy did not improve from 0.84066
47/47 [==============================] - 0s 3ms/step - loss: 0.0685 - accuracy: 0.9757 - val_loss: 0.7312 - val_accuracy: 0.7857
Epoch 238/370
38/47 [=======================>......] - ETA: 0s - loss: 0.0845 - accuracy: 0.9699
Epoch 00238: val_accuracy did not improve from 0.84066
47/47 [==============================] - 0s 3ms/step - loss: 0.0836 - accuracy: 0.9702 - val_loss: 0.6795 - val_accuracy: 0.7857
Epoch 239/370
38/47 [=======================>......] - ETA: 0s - loss: 0.0544 - accuracy: 0.9820
Epoch 00239: val_accuracy did not improve from 0.84066
47/47 [==============================] - 0s 3ms/step - loss: 0.0640 - accuracy: 0.9769 - val_loss: 0.6185 - val_accuracy: 0.7912
Epoch 240/370
45/47 [===========================>..] - ETA: 0s - loss: 0.0669 - accuracy: 0.9765
Epoch 00240: val_accuracy did not improve from 0.84066
47/47 [==============================] - 0s 4ms/ste

In [ ]:
# Calculating performance estimators for second CNN model
from sklearn.metrics import matthews_corrcoef
#import keras_metrics
#from keras import backend as K
from sklearn.metrics import confusion_matrix
from sklearn.metrics import classification_report
#import keras_metrics as km
from sklearn.metrics import f1_score 
a = np.array(pred)
aa= []
for sublist in a:
    for val in sublist:
        aa.append(val)

b= np.array(testing)
bb= []
for sublist in b:
    for val in sublist:
        bb.append(val)
sensitivity1=np.zeros(10) #...........................
specificity1=np.zeros(10) #...........................
mcc=np.zeros(10)  #...........................
accuracy1=np.zeros(10) #...........................
aucc=np.zeros(10) #...........................
tp=np.zeros(10) #...........................
fp=np.zeros(10) #...........................
fn=np.zeros(10) #...........................
tn=np.zeros(10) #...........................
for i in range(10): #...........................
  print('All observations for model', i)
  #%% sensitivity and specificity
  cm1 = confusion_matrix(b[i], a[i])
  sensitivity1[i] = cm1[0,0]/(cm1[0,0]+cm1[0,1])
  print('Sensitivity : ', sensitivity1[i] )

  specificity1[i] = cm1[1,1]/(cm1[1,0]+cm1[1,1])
  print('Specificity : ', specificity1[i])
  tp[i]=cm1[0,0]
  print('tp : ', tp[i])
  fp[i]=cm1[0,1]
  print('fp : ', fp[i])
  fn[i]=cm1[1,0]
  print('fn : ', fn[i])
  tn[i]=cm1[1,0]
  print('tn : ', tn[i])
  #%%
  from sklearn.metrics import matthews_corrcoef
  mcc[i] = matthews_corrcoef(b[i],a[i])
  print('Matthews Correlation Coefficient:', mcc[i])

  #%%
  total1=sum(sum(cm1))

  accuracy1[i]=(cm1[0,0]+cm1[1,1])/total1
  print ('Accuracy : ', accuracy1[i])

  import numpy as np
  from sklearn import metrics
  fpr, tpr, thresholds = metrics.roc_curve(b[i], a[i])
  aucc[i]=metrics.auc(fpr, tpr)
  print('AUC:', aucc[i])
  
print("AVG OF ALL:")
print('Sensitivity : ', np.mean(sensitivity1) )
print('Specificity : ', np.mean(specificity1))
print('Matthews Correlation Coefficient:', np.mean(mcc))
print('AUC:', np.mean(aucc))
print ('Accuracy : ', np.mean(accuracy1))
print('tp:',np.mean(tp))
print('fp:',np.mean(fp))
print('tn:',np.mean(tn))
print('fn:',np.mean(fn))

All observations for model 0
Sensitivity :  0.8152173913043478
Specificity :  0.8571428571428571
tp :  75.0
fp :  17.0
fn :  13.0
tn :  13.0
Matthews Correlation Coefficient: 0.6728426306078676
Accuracy :  0.8360655737704918
AUC: 0.8361801242236025
All observations for model 1
Sensitivity :  0.8695652173913043
Specificity :  0.8351648351648352
tp :  80.0
fp :  12.0
fn :  15.0
tn :  15.0
Matthews Correlation Coefficient: 0.7052356583027926
Accuracy :  0.8524590163934426
AUC: 0.8523650262780699
All observations for model 2
Sensitivity :  0.9021739130434783
Specificity :  0.7362637362637363
tp :  83.0
fp :  9.0
fn :  24.0
tn :  24.0
Matthews Correlation Coefficient: 0.6477902614023426
Accuracy :  0.819672131147541
AUC: 0.8192188246536073
All observations for model 3
Sensitivity :  0.9010989010989011
Specificity :  0.7282608695652174
tp :  82.0
fp :  9.0
fn :  25.0
tn :  25.0
Matthews Correlation Coefficient: 0.6385793989389978
Accuracy :  0.8142076502732241
AUC: 0.8146798853320592
All obs

In [ ]:
#%%  Training CNN for third type of Images (Gap with 0,2,3 (Features3))
seed = 1
numpy.random.seed(seed)
kfold = StratifiedKFold(n_splits=10, shuffle=True, random_state=seed)
cvscores = []
testing=[]
pred=[]
i=1
for train, test in kfold.split(features3, labels): #.......................................................
  model = Sequential()
  model.add(Conv2D(32, (3, 3),  input_shape=features3[0].shape))#.......................................................
  convout1 = Activation('relu')
  model.add(convout1)
  convout3 = Activation('relu')
  model.add(convout3)
  model.add(Conv2D(8,( 3, 3)))
  
  model.add(MaxPooling2D(pool_size=(2,2 )))
  model.add(Dropout(0.5))

  model.add(Flatten())
  model.add(Dense(170))
  model.add(Activation('relu'))
  model.add(Dropout(0.5))
  model.add(Dense(1))
  model.add(Activation('sigmoid'))
  model.compile(loss='binary_crossentropy', optimizer='adam', metrics=["accuracy"])
  ii=str(i)
  filepath="/content/drive/My Drive/Colab Notebooks/new-weights-bench-cv10-0,2,3-NC-"+ii+".hdf5"  #.......................................................
  checkpoint = ModelCheckpoint(filepath, monitor='val_accuracy', verbose=1, save_best_only=True, mode='max')
  callbacks_list = [checkpoint]
	# Fit the model
  model.fit(features3[train], labels[train], batch_size=35, epochs=370, verbose=1, validation_data=(features3[test], labels[test]),callbacks=callbacks_list) #.......................................................
  score2=model.evaluate(features3[train],labels[train],verbose=0) #..............................
  print("acuuurcy:")
  print(score2)
  model = Sequential()
  model.add(Conv2D(32, (3, 3),  input_shape=features3[0].shape)) #.......................................................
  convout1 = Activation('relu')
  model.add(convout1)
  convout3 = Activation('relu')
  model.add(convout3)
  model.add(Conv2D(8,( 3, 3)))
  
  model.add(MaxPooling2D(pool_size=(2,2 )))
  model.add(Dropout(0.5))
  model.add(Flatten())
  model.add(Dense(170))
  model.add(Activation('relu'))
  model.add(Dropout(0.5))
  model.add(Dense(1))
  model.add(Activation('sigmoid'))
  #model.compile(loss='binary_crossentropy', optimizer='adam', metrics=["accuracy"])
# load weights
  model.load_weights(filepath)
# Compile model (required to make predictions)
  model.compile(loss='binary_crossentropy', optimizer='adam', metrics=["accuracy"])
  print("Created model and loaded weights from file")
# load pima indians dataset
  score2=model.evaluate(features3[train],labels[train],verbose=0) #.......................................................
  print("acuuuraaacy:")
  print(score2)
  scores = model.evaluate(features3[test], labels[test], verbose=0) #.......................................................
  print("%s: %.2f%%" % (model.metrics_names[1], scores[1]*100))
  cvscores.append(scores[1] * 100)
  p = model.predict_classes(features3[test])  #.......................................................     
  pred.append(p)
  testing.append(labels[test]) 
  i=i+1
print("%.2f%% (+/- %.2f%%)" % (numpy.mean(cvscores), numpy.std(cvscores)))


Streaming output truncated to the last 5000 lines.
Epoch 00237: val_accuracy did not improve from 0.84066
47/47 [==============================] - 0s 3ms/step - loss: 0.0999 - accuracy: 0.9659 - val_loss: 0.6902 - val_accuracy: 0.8242
Epoch 238/370
37/47 [======================>.......] - ETA: 0s - loss: 0.0686 - accuracy: 0.9699
Epoch 00238: val_accuracy did not improve from 0.84066
47/47 [==============================] - 0s 3ms/step - loss: 0.0728 - accuracy: 0.9702 - val_loss: 0.6206 - val_accuracy: 0.8022
Epoch 239/370
47/47 [==============================] - ETA: 0s - loss: 0.0956 - accuracy: 0.9665
Epoch 00239: val_accuracy did not improve from 0.84066
47/47 [==============================] - 0s 4ms/step - loss: 0.0956 - accuracy: 0.9665 - val_loss: 0.6775 - val_accuracy: 0.8187
Epoch 240/370
46/47 [============================>.] - ETA: 0s - loss: 0.0827 - accuracy: 0.9727
Epoch 00240: val_accuracy did not improve from 0.84066
47/47 [==============================] - 0s 4ms/ste

In [ ]:
# Calculating performance estimators for third CNN model
from sklearn.metrics import matthews_corrcoef
#import keras_metrics
#from keras import backend as K
from sklearn.metrics import confusion_matrix
from sklearn.metrics import classification_report
#import keras_metrics as km
from sklearn.metrics import f1_score 
a = np.array(pred)
aa= []
for sublist in a:
    for val in sublist:
        aa.append(val)

b= np.array(testing)
bb= []
for sublist in b:
    for val in sublist:
        bb.append(val)
sensitivity1=np.zeros(10) #...........................
specificity1=np.zeros(10) #...........................
mcc=np.zeros(10)  #...........................
accuracy1=np.zeros(10) #...........................
aucc=np.zeros(10) #...........................
tp=np.zeros(10) #...........................
fp=np.zeros(10) #...........................
fn=np.zeros(10) #...........................
tn=np.zeros(10) #...........................
for i in range(10): #...........................
  print('All observations for model', i)
  #%% sensitivity and specificity
  cm1 = confusion_matrix(b[i], a[i])
  sensitivity1[i] = cm1[0,0]/(cm1[0,0]+cm1[0,1])
  print('Sensitivity : ', sensitivity1[i] )

  specificity1[i] = cm1[1,1]/(cm1[1,0]+cm1[1,1])
  print('Specificity : ', specificity1[i])
  tp[i]=cm1[0,0]
  print('tp : ', tp[i])
  fp[i]=cm1[0,1]
  print('fp : ', fp[i])
  fn[i]=cm1[1,0]
  print('fn : ', fn[i])
  tn[i]=cm1[1,0]
  print('tn : ', tn[i])
  #%%
  from sklearn.metrics import matthews_corrcoef
  mcc[i] = matthews_corrcoef(b[i],a[i])
  print('Matthews Correlation Coefficient:', mcc[i])

  #%%
  total1=sum(sum(cm1))

  accuracy1[i]=(cm1[0,0]+cm1[1,1])/total1
  print ('Accuracy : ', accuracy1[i])

  import numpy as np
  from sklearn import metrics
  fpr, tpr, thresholds = metrics.roc_curve(b[i], a[i])
  aucc[i]=metrics.auc(fpr, tpr)
  print('AUC:', aucc[i])
  
print("AVG OF ALL:")
print('Sensitivity : ', np.mean(sensitivity1) )
print('Specificity : ', np.mean(specificity1))
print('Matthews Correlation Coefficient:', np.mean(mcc))
print('AUC:', np.mean(aucc))
print ('Accuracy : ', np.mean(accuracy1))
print('tp:',np.mean(tp))
print('fp:',np.mean(fp))
print('tn:',np.mean(tn))
print('fn:',np.mean(fn))

All observations for model 0
Sensitivity :  0.8043478260869565
Specificity :  0.7912087912087912
tp :  74.0
fp :  18.0
fn :  19.0
tn :  19.0
Matthews Correlation Coefficient: 0.5956277667634522
Accuracy :  0.7978142076502732
AUC: 0.7977783086478739
All observations for model 1
Sensitivity :  0.8152173913043478
Specificity :  0.7802197802197802
tp :  75.0
fp :  17.0
fn :  20.0
tn :  20.0
Matthews Correlation Coefficient: 0.5958643655321052
Accuracy :  0.7978142076502732
AUC: 0.7977185857620641
All observations for model 2
Sensitivity :  0.8913043478260869
Specificity :  0.7472527472527473
tp :  82.0
fp :  10.0
fn :  23.0
tn :  23.0
Matthews Correlation Coefficient: 0.6456131887864245
Accuracy :  0.819672131147541
AUC: 0.819278547539417
All observations for model 3
Sensitivity :  0.8351648351648352
Specificity :  0.7608695652173914
tp :  76.0
fp :  15.0
fn :  22.0
tn :  22.0
Matthews Correlation Coefficient: 0.597535118830828
Accuracy :  0.7978142076502732
AUC: 0.7980172001911133
All obs

In [ ]:
#%%  Training CNN for Fourth type of Images (Gap with 1,2,3 (Features4))
seed = 1
numpy.random.seed(seed)
kfold = StratifiedKFold(n_splits=10, shuffle=True, random_state=seed)
cvscores = []
testing=[]
pred=[]
i=1
for train, test in kfold.split(features4, labels): #.......................................................
  model = Sequential()
  model.add(Conv2D(32, (3, 3),  input_shape=features4[0].shape))#.......................................................
  convout1 = Activation('relu')
  model.add(convout1)
  convout3 = Activation('relu')
  model.add(convout3)
  model.add(Conv2D(8,( 3, 3)))
  
  model.add(MaxPooling2D(pool_size=(2,2 )))
  model.add(Dropout(0.5))

  model.add(Flatten())
  model.add(Dense(170))
  model.add(Activation('relu'))
  model.add(Dropout(0.5))
  model.add(Dense(1))
  model.add(Activation('sigmoid'))
  model.compile(loss='binary_crossentropy', optimizer='adam', metrics=["accuracy"])
  ii=str(i)
  filepath="/content/drive/My Drive/Colab Notebooks/new-weights-bench-cv10-1,2,3-NC-"+ii+".hdf5"  #.......................................................
  checkpoint = ModelCheckpoint(filepath, monitor='val_accuracy', verbose=1, save_best_only=True, mode='max')
  callbacks_list = [checkpoint]
	# Fit the model
  model.fit(features4[train], labels[train], batch_size=35, epochs=370, verbose=1, validation_data=(features4[test], labels[test]), callbacks=callbacks_list) #.......................................................
  score2=model.evaluate(features4[train],labels[train],verbose=0) #..............................
  print("acuuurcy:")
  print(score2)
  model = Sequential()
  model.add(Conv2D(32, (3, 3), input_shape=features4[0].shape)) #.......................................................
  convout1 = Activation('relu')
  model.add(convout1)
  convout3 = Activation('relu')
  model.add(convout3)
  model.add(Conv2D(8,( 3, 3)))
  
  model.add(MaxPooling2D(pool_size=(2,2 )))
  model.add(Dropout(0.5))
  model.add(Flatten())
  model.add(Dense(170))
  model.add(Activation('relu'))
  model.add(Dropout(0.5))
  model.add(Dense(1))
  model.add(Activation('sigmoid'))
  #model.compile(loss='binary_crossentropy', optimizer='adam', metrics=["accuracy"])
# load weights
  model.load_weights(filepath)
# Compile model (required to make predictions)
  model.compile(loss='binary_crossentropy', optimizer='adam', metrics=["accuracy"])
  print("Created model and loaded weights from file")
# load pima indians dataset
  score2=model.evaluate(features4[train],labels[train],verbose=0) #.......................................................
  print("acuuuraaacy:")
  print(score2)
  scores = model.evaluate(features4[test], labels[test], verbose=0) #.......................................................
  print("%s: %.2f%%" % (model.metrics_names[1], scores[1]*100))
  cvscores.append(scores[1] * 100)
  p = model.predict_classes(features4[test])  #.......................................................     
  pred.append(p)
  testing.append(labels[test]) 
  i=i+1
print("%.2f%% (+/- %.2f%%)" % (numpy.mean(cvscores), numpy.std(cvscores)))


Streaming output truncated to the last 5000 lines.
Epoch 00237: val_accuracy did not improve from 0.82967
47/47 [==============================] - 0s 4ms/step - loss: 0.0824 - accuracy: 0.9732 - val_loss: 0.8335 - val_accuracy: 0.8132
Epoch 238/370
46/47 [============================>.] - ETA: 0s - loss: 0.0634 - accuracy: 0.9820
Epoch 00238: val_accuracy did not improve from 0.82967
47/47 [==============================] - 0s 4ms/step - loss: 0.0665 - accuracy: 0.9811 - val_loss: 0.6366 - val_accuracy: 0.8022
Epoch 239/370
47/47 [==============================] - ETA: 0s - loss: 0.0822 - accuracy: 0.9678
Epoch 00239: val_accuracy did not improve from 0.82967
47/47 [==============================] - 0s 4ms/step - loss: 0.0822 - accuracy: 0.9678 - val_loss: 0.7298 - val_accuracy: 0.7912
Epoch 240/370
46/47 [============================>.] - ETA: 0s - loss: 0.0585 - accuracy: 0.9783
Epoch 00240: val_accuracy did not improve from 0.82967
47/47 [==============================] - 0s 4ms/ste

In [ ]:
# Calculating performance estimators for fourth CNN model
from sklearn.metrics import matthews_corrcoef
#import keras_metrics
#from keras import backend as K
from sklearn.metrics import confusion_matrix
from sklearn.metrics import classification_report
#import keras_metrics as km
from sklearn.metrics import f1_score 
a = np.array(pred)
aa= []
for sublist in a:
    for val in sublist:
        aa.append(val)

b= np.array(testing)
bb= []
for sublist in b:
    for val in sublist:
        bb.append(val)
sensitivity1=np.zeros(10) #...........................
specificity1=np.zeros(10) #...........................
mcc=np.zeros(10)  #...........................
accuracy1=np.zeros(10) #...........................
aucc=np.zeros(10) #...........................
tp=np.zeros(10) #...........................
fp=np.zeros(10) #...........................
fn=np.zeros(10) #...........................
tn=np.zeros(10) #...........................
for i in range(10): #...........................
  print('All observations for model', i)
  #%% sensitivity and specificity
  cm1 = confusion_matrix(b[i], a[i])
  sensitivity1[i] = cm1[0,0]/(cm1[0,0]+cm1[0,1])
  print('Sensitivity : ', sensitivity1[i] )

  specificity1[i] = cm1[1,1]/(cm1[1,0]+cm1[1,1])
  print('Specificity : ', specificity1[i])
  tp[i]=cm1[0,0]
  print('tp : ', tp[i])
  fp[i]=cm1[0,1]
  print('fp : ', fp[i])
  fn[i]=cm1[1,0]
  print('fn : ', fn[i])
  tn[i]=cm1[1,0]
  print('tn : ', tn[i])
  #%%
  from sklearn.metrics import matthews_corrcoef
  mcc[i] = matthews_corrcoef(b[i],a[i])
  print('Matthews Correlation Coefficient:', mcc[i])

  #%%
  total1=sum(sum(cm1))

  accuracy1[i]=(cm1[0,0]+cm1[1,1])/total1
  print ('Accuracy : ', accuracy1[i])

  import numpy as np
  from sklearn import metrics
  fpr, tpr, thresholds = metrics.roc_curve(b[i], a[i])
  aucc[i]=metrics.auc(fpr, tpr)
  print('AUC:', aucc[i])
  
print("AVG OF ALL:")
print('Sensitivity : ', np.mean(sensitivity1) )
print('Specificity : ', np.mean(specificity1))
print('Matthews Correlation Coefficient:', np.mean(mcc))
print('AUC:', np.mean(aucc))
print ('Accuracy : ', np.mean(accuracy1))
print('tp:',np.mean(tp))
print('fp:',np.mean(fp))
print('tn:',np.mean(tn))
print('fn:',np.mean(fn))

All observations for model 0
Sensitivity :  0.8043478260869565
Specificity :  0.8021978021978022
tp :  74.0
fp :  18.0
fn :  18.0
tn :  18.0
Matthews Correlation Coefficient: 0.6065456282847587
Accuracy :  0.8032786885245902
AUC: 0.8032728141423794
All observations for model 1
Sensitivity :  0.8152173913043478
Specificity :  0.8571428571428571
tp :  75.0
fp :  17.0
fn :  13.0
tn :  13.0
Matthews Correlation Coefficient: 0.6728426306078676
Accuracy :  0.8360655737704918
AUC: 0.8361801242236025
All observations for model 2
Sensitivity :  0.8369565217391305
Specificity :  0.7802197802197802
tp :  77.0
fp :  15.0
fn :  20.0
tn :  20.0
Matthews Correlation Coefficient: 0.6182850691895679
Accuracy :  0.8087431693989071
AUC: 0.8085881509794552
All observations for model 3
Sensitivity :  0.8571428571428571
Specificity :  0.7282608695652174
tp :  78.0
fp :  13.0
fn :  25.0
tn :  25.0
Matthews Correlation Coefficient: 0.5900740105583714
Accuracy :  0.7923497267759563
AUC: 0.7927018633540373
All 

# Training SVM (Final Predictor)

**Loading one by one each four CNN models from drive for predictions (by choosing best model from 10 fold cross-validation)**

In [ ]:
filepath="/content/drive/My Drive/Colab Notebooks/new-weights-bench-cv10-0,1,2-NC-2.hdf5" #......................................
model = Sequential()
model.add(Conv2D(32, (3, 3),  input_shape=feature1[0].shape)) #...................................
convout1 = Activation('relu')
model.add(convout1)
convout3 = Activation('relu')
model.add(convout3)
model.add(Conv2D(8,( 3, 3)))
  
model.add(MaxPooling2D(pool_size=(2,2 )))
model.add(Dropout(0.5))

model.add(Flatten())
model.add(Dense(170))
model.add(Activation('relu'))
model.add(Dropout(0.5))
model.add(Dense(1))
model.add(Activation('sigmoid'))

#model.compile(loss='binary_crossentropy', optimizer='adam', metrics=["accuracy"])
# load weights
model.load_weights(filepath)
# Compile model (required to make predictions)
model.compile(loss='binary_crossentropy', optimizer='adam', metrics=["accuracy"])
print("Created model and loaded weights from file")
# load pima indians dataset
p1=model.predict_classes(feature1) #.......................
#pre.apppend(t1)
from sklearn.metrics import confusion_matrix
cm1 = confusion_matrix(label, p1) #............................
print(cm1)
total1=sum(sum(cm1))
accuracy1=(cm1[0,0]+cm1[1,1])/total1 
print(accuracy1)
scores = model.evaluate(feature1, label, verbose=0) #................................
print(scores)

Created model and loaded weights from file
[[902  11]
 [ 21 892]]
0.9824753559693319
[0.081637904047966, 0.9824753403663635]


In [ ]:
filepath="/content/drive/My Drive/Colab Notebooks/new-weights-bench-cv10-0,1,3-NC-2.hdf5" #......................................
model = Sequential()
model.add(Conv2D(32, (3, 3),  input_shape=feature2[0].shape)) #...................................
convout1 = Activation('relu')
model.add(convout1)
convout3 = Activation('relu')
model.add(convout3)
model.add(Conv2D(8,( 3, 3)))
  
model.add(MaxPooling2D(pool_size=(2,2 )))
model.add(Dropout(0.5))

model.add(Flatten())
model.add(Dense(170))
model.add(Activation('relu'))
model.add(Dropout(0.5))
model.add(Dense(1))
model.add(Activation('sigmoid'))

#model.compile(loss='binary_crossentropy', optimizer='adam', metrics=["accuracy"])
# load weights
model.load_weights(filepath)
# Compile model (required to make predictions)
model.compile(loss='binary_crossentropy', optimizer='adam', metrics=["accuracy"])
print("Created model and loaded weights from file")
# load pima indians dataset
p2=model.predict_classes(feature2) #.......................
#pre.apppend(t1)
from sklearn.metrics import confusion_matrix
cm1 = confusion_matrix(label, p2) #............................
print(cm1)
total1=sum(sum(cm1))
accuracy1=(cm1[0,0]+cm1[1,1])/total1 
print(accuracy1)
scores = model.evaluate(feature2, label, verbose=0) #................................
print(scores)

Created model and loaded weights from file
[[895  18]
 [ 16 897]]
0.9813800657174151
[0.08080616593360901, 0.981380045413971]


In [ ]:


filepath="/content/drive/My Drive/Colab Notebooks/new-weights-bench-cv10-0,2,3-NC-2.hdf5" #......................................
model = Sequential()
model.add(Conv2D(32, (3, 3),  input_shape=feature3[0].shape)) #...................................
convout1 = Activation('relu')
model.add(convout1)
convout3 = Activation('relu')
model.add(convout3)
model.add(Conv2D(8,( 3, 3)))
  
model.add(MaxPooling2D(pool_size=(2,2 )))
model.add(Dropout(0.5))

model.add(Flatten())
model.add(Dense(170))
model.add(Activation('relu'))
model.add(Dropout(0.5))
model.add(Dense(1))
model.add(Activation('sigmoid'))

#model.compile(loss='binary_crossentropy', optimizer='adam', metrics=["accuracy"])
# load weights
model.load_weights(filepath)
# Compile model (required to make predictions)
model.compile(loss='binary_crossentropy', optimizer='adam', metrics=["accuracy"])
print("Created model and loaded weights from file")
# load pima indians dataset
p3=model.predict_classes(feature3) #.......................
#pre.apppend(t1)
from sklearn.metrics import confusion_matrix
cm1 = confusion_matrix(label, p3) #............................
print(cm1)
total1=sum(sum(cm1))
accuracy1=(cm1[0,0]+cm1[1,1])/total1 
print(accuracy1)
scores = model.evaluate(feature3, label, verbose=0) #................................
print(scores)

Created model and loaded weights from file
[[896  17]
 [ 20 893]]
0.97973713033954
[0.07520582526922226, 0.9797371029853821]


In [ ]:
filepath="/content/drive/My Drive/Colab Notebooks/new-weights-bench-cv10-1,2,3-NC-2.hdf5" #......................................
model = Sequential()
model.add(Conv2D(32, (3, 3),  input_shape=feature4[0].shape)) #...................................
convout1 = Activation('relu')
model.add(convout1)
convout3 = Activation('relu')
model.add(convout3)
model.add(Conv2D(8,( 3, 3)))
  
model.add(MaxPooling2D(pool_size=(2,2 )))
model.add(Dropout(0.5))

model.add(Flatten())
model.add(Dense(170))
model.add(Activation('relu'))
model.add(Dropout(0.5))
model.add(Dense(1))
model.add(Activation('sigmoid'))

#model.compile(loss='binary_crossentropy', optimizer='adam', metrics=["accuracy"])
# load weights
model.load_weights(filepath)
# Compile model (required to make predictions)
model.compile(loss='binary_crossentropy', optimizer='adam', metrics=["accuracy"])
print("Created model and loaded weights from file")
# load pima indians dataset
p4=model.predict_classes(feature4) #.......................
#pre.apppend(t1)
from sklearn.metrics import confusion_matrix
cm1 = confusion_matrix(label, p4) #............................
print(cm1)
total1=sum(sum(cm1))
accuracy1=(cm1[0,0]+cm1[1,1])/total1 
print(accuracy1)
scores = model.evaluate(feature4, label, verbose=0) #................................
print(scores)

Created model and loaded weights from file
[[896  17]
 [ 13 900]]
0.9835706462212487
[0.08378271013498306, 0.9835706353187561]


**combining the predictions of all 4 CNN models in one feature vector:**

In [ ]:
featureee=np.zeros((1826,4))
for i in range(1826):
  featureee[i,0]=p1[i]
  featureee[i,1]=p2[i]
  featureee[i,2]=p3[i]
  featureee[i,3]=p4[i]

**Calculating Amino Acid  Composition (AAC) Features:**

In [ ]:
c="/content/drive/My Drive/Colab Notebooks/allseq.csv"
with open(c) as f:
    content = f.read() 
s=0
dat=content.split("\n") 
for i in dat:
    dat[s]=list(dat[s])
    s=s+1
import numpy as np    
feature = np.zeros((1826,20,))
print(feature)  
ppp=20
aa=0; rr=0; nn=0; dd=0; cc=0; qq=0; ee=0; gg=0; hh=0; ii=0; ll=0; kk=0; mm=0; ff=0; pp=0; ss=0; tt=0; ww=0; yy=0; vv=0; 
sss=0;
spsp=1;


for i in range(1826):
    word = dat[spsp]
    v=0
    for l in word:
        if word[v]=='A':
            aa=aa+1
        elif word[v]=='R':
            rr=rr+1
        elif word[v]=='N':
            nn=nn+1
        elif word[v]=='D':
            dd=dd+1
        elif word[v]=='C':
            cc=cc+1
        elif word[v]=='Q':
            qq=qq+1
        elif word[v]=='E':
            ee=ee+1
        elif word[v]=='G':
            gg=gg+1
        elif word[v]=='H':
            hh=hh+1
        elif word[v]=='I':
            ii=ii+1
        elif word[v]=='L':
            ll=ll+1
        elif word[v]=='K':
            kk=kk+1
        elif word[v]=='M':
            mm=mm+1
        elif word[v]=='F':
            ff=ff+1
        elif word[v]=='P':
            pp=pp+1
        elif word[v]=='S':
            ss=ss+1
        elif word[v]=='T':
            tt=tt+1
        elif word[v]=='W':
            ww=ww+1
        elif word[v]=='Y':
            yy=yy+1
        else:
            vv=vv+1
        v=v+1    
    
    #aa=aa/20; rr=rr/20; nn=nn/20; dd=dd/20; cc=cc/20; qq=qq/20; ee=ee/20; gg=gg/20; hh=hh/20; ii=ii/20; ll=ll/20; kk=kk/20; mm=mm/20; ff=ff/20; pp=pp/20; ss=ss/20; tt=tt/20; ww=ww/20; yy=yy/20; vv=vv/20;
    feature[sss][0]=aa; feature[sss][1]=rr; feature[sss][2]=nn; feature[sss][3]=dd; feature[sss][4]=cc; feature[sss][5]=qq; feature[sss][6]=ee; feature[sss][7]=gg; feature[sss][8]=hh; feature[sss][9]=ii; feature[sss][10]=ll; feature[sss][11]=kk; feature[sss][12]=mm; feature[sss][13]=ff; feature[sss][14]=pp; feature[sss][15]=ss; feature[sss][16]=tt; feature[sss][17]=ww; feature[sss][18]=yy; feature[sss][19]=vv; 
    aa=0; rr=0; nn=0; dd=0; cc=0; qq=0; ee=0; gg=0; hh=0; ii=0; ll=0; kk=0; mm=0; ff=0; pp=0; ss=0; tt=0; ww=0; yy=0; vv=0;
    sss=sss+1
    spsp=spsp+2

[[0. 0. 0. ... 0. 0. 0.]
 [0. 0. 0. ... 0. 0. 0.]
 [0. 0. 0. ... 0. 0. 0.]
 ...
 [0. 0. 0. ... 0. 0. 0.]
 [0. 0. 0. ... 0. 0. 0.]
 [0. 0. 0. ... 0. 0. 0.]]


**Combining the predictions of four CNN models with AAC features and generating new feature vector of 24 features to input SVM**

In [ ]:
inputt=np.zeros((1826,24))
inputt[:,0:4]=featureee[:,:]
inputt[:,4:]=feature[:,:]

**Training SVM**

In [ ]:
from sklearn.utils import shuffle
input2,labels=shuffle(inputt,label, random_state=1)

from sklearn.svm import SVC  
from sklearn.metrics import accuracy_score
import numpy as np
from sklearn.model_selection import train_test_split
from sklearn import datasets
from sklearn import svm
from sklearn.svm import SVC  
from sklearn.metrics import accuracy_score
import numpy as np
from sklearn.model_selection import train_test_split
from sklearn import datasets
from sklearn import svm
import numpy as np
from sklearn.model_selection import train_test_split
from sklearn import datasets
from sklearn import svm  
from sklearn.metrics import classification_report, confusion_matrix
import pickle


seed = 1
np.random.seed(seed)
kfold = StratifiedKFold(n_splits=10, shuffle=True, random_state=seed) #......................
cvscores = []
testing=[]
pred=[]
i=1
for train, test in kfold.split(input2, labels):
  svclassifier = SVC(kernel='rbf', gamma=.5, C=2)  
  svclassifier.fit(input2[train], labels[train])
  y_pred = svclassifier.predict(input2[test])
  print(confusion_matrix(labels[test],y_pred))  
  #print(classification_report(labels[test],y_pred))  
  #clf_predictions = svclassifier.predict(features2[test])
  print("Accuracy: {}%".format(svclassifier.score(input2[test], labels[test]) * 100 ))
  score2=svclassifier.score(input2[test], labels[test])
  cvscores.append(score2 * 100)
  p = svclassifier.predict(input2[test])       
  pred.append(p)
  testing.append(labels[test])
  ii=str(i)
  # save the model to disk
  filename = "/content/drive/My Drive/Colab Notebooks/new-svm-benc10-NC-"+ii+".sav" #...........................
  pickle.dump(svclassifier, open(filename, 'wb'))
 
  
  i=i+1
print("%.2f%% (+/- %.2f%%)" % (np.mean(cvscores), np.std(cvscores)))


[[92  0]
 [ 3 88]]
Accuracy: 98.36065573770492%
[[89  3]
 [20 71]]
Accuracy: 87.43169398907104%
[[92  0]
 [ 8 83]]
Accuracy: 95.62841530054644%
[[91  0]
 [13 79]]
Accuracy: 92.89617486338798%
[[91  0]
 [ 7 85]]
Accuracy: 96.17486338797814%
[[91  0]
 [ 3 89]]
Accuracy: 98.36065573770492%
[[91  0]
 [ 4 87]]
Accuracy: 97.8021978021978%
[[91  0]
 [ 5 86]]
Accuracy: 97.25274725274726%
[[91  0]
 [ 3 88]]
Accuracy: 98.35164835164835%
[[91  0]
 [ 7 84]]
Accuracy: 96.15384615384616%
95.84% (+/- 3.23%)


**Calculating Performance estimatores for SVM**

In [ ]:
par=10
from sklearn.metrics import matthews_corrcoef
#import keras_metrics
#from keras import backend as K
from sklearn.metrics import confusion_matrix
from sklearn.metrics import classification_report
#import keras_metrics as km
from sklearn.metrics import f1_score 
a = np.array(pred)
aa= []
for sublist in a:
    for val in sublist:
        aa.append(val)

b= np.array(testing)
bb= []
for sublist in b:
    for val in sublist:
        bb.append(val)
sensitivity1=np.zeros(par) #...........................
specificity1=np.zeros(par) #...........................
mcc=np.zeros(par)  #...........................
accuracy1=np.zeros(par) #...........................
aucc=np.zeros(par) #...........................
tp=np.zeros(par) #...........................
fp=np.zeros(par) #...........................
fn=np.zeros(par) #...........................
tn=np.zeros(par) #...........................
for i in range(par): #...........................
  print('All observations for model', i)
  #%% sensitivity and specificity
  cm1 = confusion_matrix(b[i], a[i])
  sensitivity1[i] = cm1[0,0]/(cm1[0,0]+cm1[0,1])
  print('Sensitivity : ', sensitivity1[i] )

  specificity1[i] = cm1[1,1]/(cm1[1,0]+cm1[1,1])
  print('Specificity : ', specificity1[i])
  tp[i]=cm1[0,0]
  print('tp : ', tp[i])
  fp[i]=cm1[0,1]
  print('fp : ', fp[i])
  fn[i]=cm1[1,0]
  print('fn : ', fn[i])
  tn[i]=cm1[1,0]
  print('tn : ', tn[i])
  #%%
  from sklearn.metrics import matthews_corrcoef
  mcc[i] = matthews_corrcoef(b[i],a[i])
  print('Matthews Correlation Coefficient:', mcc[i])

  #%%
  total1=sum(sum(cm1))

  accuracy1[i]=(cm1[0,0]+cm1[1,1])/total1
  print ('Accuracy : ', accuracy1[i])

  import numpy as np
  from sklearn import metrics
  fpr, tpr, thresholds = metrics.roc_curve(b[i], a[i])
  aucc[i]=metrics.auc(fpr, tpr)
  print('AUC:', aucc[i])
  
print("AVG OF ALL:")
print('Sensitivity : ', np.mean(sensitivity1) )
print('Specificity : ', np.mean(specificity1))
print('Matthews Correlation Coefficient:', np.mean(mcc))
print('AUC:', np.mean(aucc))
print ('Accuracy : ', np.mean(accuracy1))
print('tp:',np.mean(tp))
print('fp:',np.mean(fp))
print('tn:',np.mean(tn))
print('fn:',np.mean(fn))

All observations for model 0
Sensitivity :  1.0
Specificity :  0.967032967032967
tp :  92.0
fp :  0.0
fn :  3.0
tn :  3.0
Matthews Correlation Coefficient: 0.9677267609524421
Accuracy :  0.9836065573770492
AUC: 0.9835164835164836
All observations for model 1
Sensitivity :  0.967391304347826
Specificity :  0.7802197802197802
tp :  89.0
fp :  3.0
fn :  20.0
tn :  20.0
Matthews Correlation Coefficient: 0.7616601481585566
Accuracy :  0.8743169398907104
AUC: 0.8738055422838031
All observations for model 2
Sensitivity :  1.0
Specificity :  0.9120879120879121
tp :  92.0
fp :  0.0
fn :  8.0
tn :  8.0
Matthews Correlation Coefficient: 0.9160354136827238
Accuracy :  0.9562841530054644
AUC: 0.956043956043956
All observations for model 3
Sensitivity :  1.0
Specificity :  0.8586956521739131
tp :  91.0
fp :  0.0
fn :  13.0
tn :  13.0
Matthews Correlation Coefficient: 0.8668094921331757
Accuracy :  0.9289617486338798
AUC: 0.9293478260869565
All observations for model 4
Sensitivity :  1.0
Specificity 