In [ ]:
from google.colab import drive
drive.mount('/content/drive/')

Go to this URL in a browser: https://accounts.google.com/o/oauth2/auth?client_id=947318989803-6bn6qk8qdgf4n4g3pfee6491hc0brc4i.apps.googleusercontent.com&redirect_uri=urn%3aietf%3awg%3aoauth%3a2.0%3aoob&scope=email%20https%3a%2f%2fwww.googleapis.com%2fauth%2fdocs.test%20https%3a%2f%2fwww.googleapis.com%2fauth%2fdrive%20https%3a%2f%2fwww.googleapis.com%2fauth%2fdrive.photos.readonly%20https%3a%2f%2fwww.googleapis.com%2fauth%2fpeopleapi.readonly&response_type=code

Enter your authorization code:
··········
Mounted at /content/drive/


In [ ]:
# In following sections, the g-gap features are further processed to test CNN
c="/content/drive/My Drive/Colab Notebooks/allseq_ind.csv"
with open(c) as f:
    content = f.read() 
s=0
dat=content.split("\n") 
for i in dat:
    dat[s]=list(dat[s])
    s=s+1
          

    
import numpy as np
lm=1
tp=np.zeros(772)
for h in range(772):
    tp[h]=len(dat[lm])
    lm=lm+2
#%%
c="/content/drive/My Drive/Colab Notebooks/zero_ind.csv"
with open(c) as f:
    content0 = f.read() 
    
dat0=content0.split("\n") 
s=0
for i in range(len(dat0)):
    dat0[s]=dat0[s].split(",")
    s=s+1
    
   
import numpy as np
dataaa0=np.zeros((772,400))
ii=0; jj=0
for i in range(772):
    for j in range(400):
        dataaa0[i][j]=float(dat0[i][j])
        
tc=0
for i in range(772):
    tc=tp[i]-1
    dataaa0[i]=dataaa0[i]*tc
    
#%%
c="/content/drive/My Drive/Colab Notebooks/one_ind.csv"
with open(c) as f:
    content1 = f.read() 
    
dat1=content1.split("\n") 
s=0
for i in range(len(dat1)):
    dat1[s]=dat1[s].split(",")
    s=s+1
    
   
import numpy as np
dataaa1=np.zeros((772,400))
ii=0; jj=0
for i in range(772):
    for j in range(400):
        dataaa1[i][j]=float(dat1[i][j])
        
tc=0
for i in range(772):
    tc=tp[i]-1
    dataaa1[i]=dataaa1[i]*tc
    
#%%
c="/content/drive/My Drive/Colab Notebooks/two_ind.csv"
with open(c) as f:
    content2 = f.read() 
    
dat2=content2.split("\n") 
s=0
for i in range(len(dat2)):
    dat2[s]=dat2[s].split(",")
    s=s+1
    
   
import numpy as np
dataaa2=np.zeros((772,400))
ii=0; jj=0
for i in range(772):
    for j in range(400):
        dataaa2[i][j]=float(dat2[i][j])
        
tc=0
for i in range(772):
    tc=tp[i]-1
    dataaa2[i]=dataaa2[i]*tc
#%%
c="/content/drive/My Drive/Colab Notebooks/three_ind.csv"
with open(c) as f:
    content3 = f.read() 
    
dat3=content3.split("\n") 
s=0
for i in range(len(dat3)):
    dat3[s]=dat3[s].split(",")
    s=s+1
    
   
import numpy as np
dataaa3=np.zeros((772,400))
ii=0; jj=0
for i in range(772):
    for j in range(400):
        dataaa3[i][j]=float(dat3[i][j])
        
tc=0
for i in range(772):
    tc=tp[i]-1
    dataaa3[i]=dataaa3[i]*tc 

In [ ]:
a = np.reshape(dataaa0,[772,20,20])
b = np.reshape(dataaa1,[772,20,20])
c = np.reshape(dataaa2,[772,20,20])
feature1=np.zeros((772,20,20,3))
for i in range(772):
  data = np.zeros( (20,20,3))
  data[:,:,0]=a[i,:,:]
  data[:,:,1]=b[i,:,:]
  data[:,:,2]=c[i,:,:]
  feature1[i]=data                
                  

In [ ]:
a = np.reshape(dataaa0,[772,20,20])
b = np.reshape(dataaa1,[772,20,20])
c = np.reshape(dataaa3,[772,20,20])
feature2=np.zeros((772,20,20,3))
for i in range(772):
  data = np.zeros( (20,20,3))
  data[:,:,0]=a[i,:,:]
  data[:,:,1]=b[i,:,:]
  data[:,:,2]=c[i,:,:]
  feature2[i]=data 

In [ ]:
a = np.reshape(dataaa0,[772,20,20])
b = np.reshape(dataaa2,[772,20,20])
c = np.reshape(dataaa3,[772,20,20])
feature3=np.zeros((772,20,20,3))
for i in range(772):
  data = np.zeros( (20,20,3))
  data[:,:,0]=a[i,:,:]
  data[:,:,1]=b[i,:,:]
  data[:,:,2]=c[i,:,:]
  feature3[i]=data                
                  

In [ ]:
a = np.reshape(dataaa1,[772,20,20])
b = np.reshape(dataaa2,[772,20,20])
c = np.reshape(dataaa3,[772,20,20])
feature4=np.zeros((772,20,20,3))
for i in range(772):
  data = np.zeros( (20,20,3))
  data[:,:,0]=a[i,:,:]
  data[:,:,1]=b[i,:,:]
  data[:,:,2]=c[i,:,:]
  feature4[i]=data     

In [ ]:
import numpy as np
label=np.zeros(772)
for i in range(386):
    label[i]=0
j=386  
for k in range(386):
    label[j]=1
    j=j+1

In [ ]:
import os,cv2
import numpy as np
import matplotlib.pyplot as plt

from sklearn.utils import shuffle
from sklearn.model_selection import train_test_split

from keras import backend as K
K.set_image_data_format('channels_last')




from keras.utils import np_utils
from keras.models import Sequential
from keras.layers  import Dense, Dropout, Activation, Flatten
from keras.layers import Conv2D, MaxPooling2D
!pip install adam
import adam
from keras.optimizers import SGD,RMSprop
from keras.models import Sequential
from keras.layers import Dense
from sklearn.model_selection import StratifiedKFold
import numpy
from keras.callbacks import ModelCheckpoint
from keras.models import Sequential
from keras.layers import Dense
from keras.callbacks import ModelCheckpoint
import matplotlib.pyplot as plt
import numpy

In [ ]:
filepath="/content/drive/My Drive/Colab Notebooks/new-weights-bench-cv10-0,1,2-NC-2.hdf5" #.............................
model = Sequential()
model.add(Conv2D(32, (3, 3),  input_shape=feature1[0].shape)) #............................
convout1 = Activation('relu')
model.add(convout1)
convout3 = Activation('relu')
model.add(convout3)
model.add(Conv2D(8,( 3, 3)))
  
model.add(MaxPooling2D(pool_size=(2,2 )))
model.add(Dropout(0.5))

model.add(Flatten())
model.add(Dense(170))
model.add(Activation('relu'))
model.add(Dropout(0.5))
model.add(Dense(1))
model.add(Activation('sigmoid'))

#model.compile(loss='binary_crossentropy', optimizer='adam', metrics=["accuracy"])
# load weights
model.load_weights(filepath)
# Compile model (required to make predictions)
model.compile(loss='binary_crossentropy', optimizer='adam', metrics=["accuracy"])
print("Created model and loaded weights from file")
# load pima indians dataset
p1=model.predict_classes(feature1) #................
#pre.apppend(t1)
from sklearn.metrics import confusion_matrix
cm1 = confusion_matrix(label, p1)#...............................
print(cm1)
total1=sum(sum(cm1))
accuracy1=(cm1[0,0]+cm1[1,1])/total1
print(accuracy1)
scores = model.evaluate(feature1, label, verbose=0)#.............................
print(scores)

Created model and loaded weights from file
Instructions for updating:
Please use instead:* `np.argmax(model.predict(x), axis=-1)`,   if your model does multi-class classification   (e.g. if it uses a `softmax` last-layer activation).* `(model.predict(x) > 0.5).astype("int32")`,   if your model does binary classification   (e.g. if it uses a `sigmoid` last-layer activation).
[[280 106]
 [ 53 333]]
0.7940414507772021
[3.1573245525360107, 0.7940414547920227]


In [ ]:
filepath="/content/drive/My Drive/Colab Notebooks/new-weights-bench-cv10-0,1,3-NC-2.hdf5" #.............................
model = Sequential()
model.add(Conv2D(32, (3, 3),  input_shape=feature2[0].shape)) #............................
convout1 = Activation('relu')
model.add(convout1)
convout3 = Activation('relu')
model.add(convout3)
model.add(Conv2D(8,( 3, 3)))
  
model.add(MaxPooling2D(pool_size=(2,2 )))
model.add(Dropout(0.5))

model.add(Flatten())
model.add(Dense(170))
model.add(Activation('relu'))
model.add(Dropout(0.5))
model.add(Dense(1))
model.add(Activation('sigmoid'))

#model.compile(loss='binary_crossentropy', optimizer='adam', metrics=["accuracy"])
# load weights
model.load_weights(filepath)
# Compile model (required to make predictions)
model.compile(loss='binary_crossentropy', optimizer='adam', metrics=["accuracy"])
print("Created model and loaded weights from file")
# load pima indians dataset
p2=model.predict_classes(feature2) #................
#pre.apppend(t1)
from sklearn.metrics import confusion_matrix
cm1 = confusion_matrix(label, p2)#...............................
print(cm1)
total1=sum(sum(cm1))
accuracy1=(cm1[0,0]+cm1[1,1])/total1
print(accuracy1)
scores = model.evaluate(feature2, label, verbose=0)#.............................
print(scores)

Created model and loaded weights from file
[[259 127]
 [ 48 338]]
0.7733160621761658
[3.298546552658081, 0.7733160853385925]


In [ ]:
filepath="/content/drive/My Drive/Colab Notebooks/new-weights-bench-cv10-0,2,3-NC-2.hdf5" #.............................
model = Sequential()
model.add(Conv2D(32, (3, 3),  input_shape=feature3[0].shape)) #............................
convout1 = Activation('relu')
model.add(convout1)
convout3 = Activation('relu')
model.add(convout3)
model.add(Conv2D(8,( 3, 3)))
  
model.add(MaxPooling2D(pool_size=(2,2 )))
model.add(Dropout(0.5))

model.add(Flatten())
model.add(Dense(170))
model.add(Activation('relu'))
model.add(Dropout(0.5))
model.add(Dense(1))
model.add(Activation('sigmoid'))

#model.compile(loss='binary_crossentropy', optimizer='adam', metrics=["accuracy"])
# load weights
model.load_weights(filepath)
# Compile model (required to make predictions)
model.compile(loss='binary_crossentropy', optimizer='adam', metrics=["accuracy"])
print("Created model and loaded weights from file")
# load pima indians dataset
p3=model.predict_classes(feature3) #................
#pre.apppend(t1)
from sklearn.metrics import confusion_matrix
cm1 = confusion_matrix(label, p3)#...............................
print(cm1)
total1=sum(sum(cm1))
accuracy1=(cm1[0,0]+cm1[1,1])/total1
print(accuracy1)
scores = model.evaluate(feature3, label, verbose=0)#.............................
print(scores)

Created model and loaded weights from file
[[235 151]
 [ 51 335]]
0.7383419689119171
[3.506981134414673, 0.7383419871330261]


In [ ]:
filepath="/content/drive/My Drive/Colab Notebooks/new-weights-bench-cv10-1,2,3-NC-2.hdf5" #.............................
model = Sequential()
model.add(Conv2D(32, (3, 3),  input_shape=feature4[0].shape)) #............................
convout1 = Activation('relu')
model.add(convout1)
convout3 = Activation('relu')
model.add(convout3)
model.add(Conv2D(8,( 3, 3)))
  
model.add(MaxPooling2D(pool_size=(2,2 )))
model.add(Dropout(0.5))

model.add(Flatten())
model.add(Dense(170))
model.add(Activation('relu'))
model.add(Dropout(0.5))
model.add(Dense(1))
model.add(Activation('sigmoid'))

#model.compile(loss='binary_crossentropy', optimizer='adam', metrics=["accuracy"])
# load weights
model.load_weights(filepath)
# Compile model (required to make predictions)
model.compile(loss='binary_crossentropy', optimizer='adam', metrics=["accuracy"])
print("Created model and loaded weights from file")
# load pima indians dataset
p4=model.predict_classes(feature4) #................
#pre.apppend(t1)
from sklearn.metrics import confusion_matrix
cm1 = confusion_matrix(label, p4)#...............................
print(cm1)
total1=sum(sum(cm1))
accuracy1=(cm1[0,0]+cm1[1,1])/total1
print(accuracy1)
scores = model.evaluate(feature4, label, verbose=0)#.............................
print(scores)

Created model and loaded weights from file
[[261 125]
 [ 49 337]]
0.7746113989637305
[2.468719959259033, 0.7746114134788513]


In [ ]:
featureee=np.zeros((772,4))
for i in range(772):
  featureee[i,0]=p1[i]
  featureee[i,1]=p2[i]
  featureee[i,2]=p3[i]
  featureee[i,3]=p4[i]
  

In [ ]:
c="/content/drive/My Drive/Colab Notebooks/allseq_ind.csv"
with open(c) as f:
    content = f.read() 
s=0
dat=content.split("\n") 
for i in dat:
    dat[s]=list(dat[s])
    s=s+1
import numpy as np    
feature = np.zeros((772,20,))
print(feature)  
ppp=20
aa=0; rr=0; nn=0; dd=0; cc=0; qq=0; ee=0; gg=0; hh=0; ii=0; ll=0; kk=0; mm=0; ff=0; pp=0; ss=0; tt=0; ww=0; yy=0; vv=0; 
sss=0;
spsp=1;


for i in range(772):
    word = dat[spsp]
    v=0
    for l in word:
        if word[v]=='A':
            aa=aa+1
        elif word[v]=='R':
            rr=rr+1
        elif word[v]=='N':
            nn=nn+1
        elif word[v]=='D':
            dd=dd+1
        elif word[v]=='C':
            cc=cc+1
        elif word[v]=='Q':
            qq=qq+1
        elif word[v]=='E':
            ee=ee+1
        elif word[v]=='G':
            gg=gg+1
        elif word[v]=='H':
            hh=hh+1
        elif word[v]=='I':
            ii=ii+1
        elif word[v]=='L':
            ll=ll+1
        elif word[v]=='K':
            kk=kk+1
        elif word[v]=='M':
            mm=mm+1
        elif word[v]=='F':
            ff=ff+1
        elif word[v]=='P':
            pp=pp+1
        elif word[v]=='S':
            ss=ss+1
        elif word[v]=='T':
            tt=tt+1
        elif word[v]=='W':
            ww=ww+1
        elif word[v]=='Y':
            yy=yy+1
        else:
            vv=vv+1
        v=v+1    
    
    #aa=aa/20; rr=rr/20; nn=nn/20; dd=dd/20; cc=cc/20; qq=qq/20; ee=ee/20; gg=gg/20; hh=hh/20; ii=ii/20; ll=ll/20; kk=kk/20; mm=mm/20; ff=ff/20; pp=pp/20; ss=ss/20; tt=tt/20; ww=ww/20; yy=yy/20; vv=vv/20;
    feature[sss][0]=aa; feature[sss][1]=rr; feature[sss][2]=nn; feature[sss][3]=dd; feature[sss][4]=cc; feature[sss][5]=qq; feature[sss][6]=ee; feature[sss][7]=gg; feature[sss][8]=hh; feature[sss][9]=ii; feature[sss][10]=ll; feature[sss][11]=kk; feature[sss][12]=mm; feature[sss][13]=ff; feature[sss][14]=pp; feature[sss][15]=ss; feature[sss][16]=tt; feature[sss][17]=ww; feature[sss][18]=yy; feature[sss][19]=vv; 
    aa=0; rr=0; nn=0; dd=0; cc=0; qq=0; ee=0; gg=0; hh=0; ii=0; ll=0; kk=0; mm=0; ff=0; pp=0; ss=0; tt=0; ww=0; yy=0; vv=0;
    sss=sss+1
    spsp=spsp+2

[[0. 0. 0. ... 0. 0. 0.]
 [0. 0. 0. ... 0. 0. 0.]
 [0. 0. 0. ... 0. 0. 0.]
 ...
 [0. 0. 0. ... 0. 0. 0.]
 [0. 0. 0. ... 0. 0. 0.]
 [0. 0. 0. ... 0. 0. 0.]]


In [ ]:
inputt=np.zeros((772,24))
inputt[:,0:4]=featureee[:,:]
inputt[:,4:]=feature[:,:]

In [ ]:
import pickle
filename='/content/drive/My Drive/Colab Notebooks/new-svm-benc10-NC-4.sav'
loaded_model = pickle.load(open(filename, 'rb'))
result = loaded_model.score(inputt, label)
result1=loaded_model.predict(inputt)
print(result)

0.8950777202072538


In [ ]:
cm1 = confusion_matrix(label, result1)
sensitivity1 = cm1[0,0]/(cm1[0,0]+cm1[0,1])
print('Sensitivity : ', sensitivity1 )

specificity1 = cm1[1,1]/(cm1[1,0]+cm1[1,1])
print('Specificity : ', specificity1)
tp=cm1[0,0]
print('tp : ', tp)
fp=cm1[0,1]
print('fp : ', fp)
fn=cm1[1,0]
print('fn : ', fn)
tn=cm1[1,0]
print('tn : ', tn)
#%%
from sklearn.metrics import matthews_corrcoef
mcc = matthews_corrcoef(label,result1)
print('Matthews Correlation Coefficient:', mcc)

  #%%
total1=sum(sum(cm1))

accuracy1=(cm1[0,0]+cm1[1,1])/total1
print ('Accuracy : ', accuracy1)

import numpy as np
from sklearn import metrics
fpr, tpr, thresholds = metrics.roc_curve(label, result1)
aucc=metrics.auc(fpr, tpr)
print('AUC:', aucc)

Sensitivity :  0.9481865284974094
Specificity :  0.8419689119170984
tp :  366
fp :  20
fn :  61
tn :  61
Matthews Correlation Coefficient: 0.7946508537062464
Accuracy :  0.8950777202072538
AUC: 0.8950777202072538
